
package com.fxs.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestServer", targetNamespace = "http://server.fxs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://server.fxs.com/", className = "com.fxs.server.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://server.fxs.com/", className = "com.fxs.server.TestResponse")
    public String test(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
